# Kubernetes Secret for Todo App
apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  JWT_SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  DATABASE_URL: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfcjJBbFA4VEVSb2pPQGVwLXNpbGVudC1oYWxsLWE0d2wwbXdsLXBvb2xlci51cy1lYXN0LTEuYXdzLm5lb24udGVjaC9uZW9uZGI/c3NsbW9kZT1yZXF1aXJlJmNoYW5uZWxfYmluZGluZz1yZXF1aXJl
  OPENROUTER_API_KEY: c2stb3ItdjEtNmQzYWMxNDA2MDAxNWQxZjAzZWUzNzg2MzIzMGM5YWRhOWQ4ZmE3ZjM0ZTBmMWQ1YjUyNWM3NjgyNGEyM2UyYw==
